### ISSUE TITLE
Set isn't supported in older versions of node

### ISSUE THREAD

**Issue by fresheneesz** [andris9/smtp-server#14]
```
ReferenceError: Set is not defined
    at new SMTPServer (/root/email/node_modules/smtp-server/lib/smtp-server.js:83:28)
    at Object.<anonymous> (/root/email/emailServer.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

Looks like you're not even doing anything that couldn't be done just as well with a regular array. Any reason you're using a `Set`? Yes I know I should upgrade node, but i'm trying to do something quick with an email server and I don't want to go to all the trouble to figure out how to correctly update node (not only on the machine i'm using, but on all my dev's machines as well - automatic you know?).

**Comment by andris9** [comment]
I use other node 0.12 specific methods as well (mostly with Buffer and TLS), so not using Set would not make the module usable for v0.10. Set is a great and efficient data structure, lot more convenient that using arrays for the same stuff (eg. `set.delete(value)` vs `array.splice(array.indexOf(value), 1)` or `set.has(value)` vs `array.indexOf(value)>=0`)
