### ISSUE TITLE
 Object #<Object> has no method 'createSecureContext'

### ISSUE THREAD

**Issue by fresheneesz** [andris9/smtp-server#15]
I'm just testing this out, sending email to it from gmail: 

```
var smtp = require('smtp-server')
var SMTPServer = smtp.SMTPServer

var port = 465

var server = new SMTPServer({
    onData: function(stream, session, callback){
        stream.pipe(process.stdout); // print message to console
        stream.on('end', callback);
    },
    onRcptTo: function(address, session, callback){
        console.log("RcptTo: "+address)
        return callback(); // Accept the address
    } ,
    onMailFrom: function(address, session, callback){
        console.log("MailFrom: "+address)
        return callback(); // Accept the address
    },
    onAuth: function(auth, session, callback){
        console.log("Auth: "+auth.method+' by '+auth.username)
        callback(null, {})
    }
})

server.listen(port, function() {
    console.log("Listening for email on port "+port)
});

server.on('error', function(err){
    console.log('Error %s', err.message);
});
```

This is the output for the whole run of the program, when i start it, then send it an email from gmail:

```
[2015-07-26 23:17:23] INFO: SMTP Server listening on 0.0.0.0:25
Listening for email on port 465
[2015-07-26 23:18:19] INFO: [XzmZ5PT5c/s/] Connection from mail-wi0-f180.google.com
[2015-07-26 23:18:19] DEBUG: [XzmZ5PT5c/s/] S: 220 ecto-1 ESMTP
[2015-07-26 23:18:19] DEBUG: [XzmZ5PT5c/s/] C: EHLO mail-wi0-f180.google.com
[2015-07-26 23:18:19] DEBUG: [XzmZ5PT5c/s/] S: 250-OK: Nice to meet you mail-wi0-f180.google.com
250-PIPELINING
250-8BITMIME
250-SMTPUTF8
250-AUTH LOGIN PLAIN
250 STARTTLS
[2015-07-26 23:18:20] DEBUG: [XzmZ5PT5c/s/] C: STARTTLS
[2015-07-26 23:18:20] DEBUG: [XzmZ5PT5c/s/] S: 220 Ready to start TLS

/root/email/node_modules/smtp-server/lib/smtp-connection.js:503
    var secureContext = tls.createSecureContext(tlsOptions(this._server.option
                            ^
TypeError: Object #<Object> has no method 'createSecureContext'
    at SMTPConnection.handler_STARTTLS (/root/email/node_modules/smtp-server/lib/smtp-connection.js:503:29)
    at SMTPConnection._onCommand (/root/email/node_modules/smtp-server/lib/smtp-connection.js:297:13)
    at SMTPStream.<anonymous> (/root/email/node_modules/smtp-server/lib/smtp-stream.js:134:18)
    at SMTPStream._write (/root/email/node_modules/smtp-server/lib/smtp-stream.js:138:9)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at SMTPStream.Writable.write (_stream_writable.js:182:11)
    at write (_stream_readable.js:601:24)
    at flow (_stream_readable.js:610:7)
    at Socket.pipeOnReadable (_stream_readable.js:642:5)
```

Is this simply because I don't have tls set up? I would have thought gmail would be able to send to servers that don't have tls set up..

**Comment by fresheneesz** [comment]
Adding `secure:true` along with my key and cert seems to cause the server to not receive mail at all. Once I add those things and retest, instead of getting some debug messages and an error, I get nothing at all - no messages, no output. Its just sitting there listening for email.. Something seems broken. It should either give me an error i can deal with, or it should be giving me the email I sent it.

What might be going on?

**Comment by andris9** [comment]
Upgrade node to 0.12 or iojs as createSecureContext is not available in older versions of node

**Comment by fresheneesz** [comment]
Got it - would have expected at least an error tho. Any reason no error is happening?
