### ISSUE TITLE
`server.close` throws `TypeError: callback is not a function` when called without a parameter

### ISSUE THREAD

**Issue by fresheneesz** [andris9/smtp-server#33]
When calling `server.close()` without any parameters, I get the following error:

```
TypeError: callback is not a function
    at SMTPServer.<anonymous> (D:\billysFile\code\tests\node.js\node_modules\smtp-server\lib\smtp-server.js:126:9)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitCloseNT (net.js:1521:8)
    at doNTCallback1 (node.js:441:9)
    at process._tickCallback (node.js:363:17)
```

It seems it requires a callback. Shouldn't the callback be optional?

**Comment by andris9** [comment]
Updated code to not require callback for close
