### ISSUE TITLE
Problem sending with simple example (smtp-server and smtp-connection)

### ISSUE THREAD

**Issue by artzstudio** [andris9/smtp-server#53]
I'm trying to create a quick example showing how smtp-server and smtp-connection play with eachother.  I do not get any errors, but the mail is not sending.  Hoping it is just a simple mistake/wrong assumption on my part.  I'm running this on OS X.  Help appreciated!

```javascript
var SMTPServer = require('smtp-server').SMTPServer;

var server = new SMTPServer({
  secure: false,
  authMethods: ['PLAIN'],
  disabledCommands: ['STARTTLS'],
  logger: true,
  onAuth: function (auth, session, callback) {
    if (auth.username === 'foo' && auth.password === 'bar') {
      console.log('Logging in `foo`.');
      callback(null, { user: 'foo' });
    } else {
      console.log('Invalid username or password for `foo`.');
      callback(new Error('Invalid username or password.'));
    }
  }
});
server.listen(2500, function () {
  console.log('SMTP server listening on port 2500.');
});
server.on('error', function(err){
  console.log('Error %s', err.message);
});

var SMTPConnection = require('smtp-connection');
var options = {
  port: 2500,
  host: 'localhost',
  secure: false,
  ignoreTLS: true,
  logger: true,
  debug: true,
  authMethod: 'PLAIN'
};
var mailcomposer = require("mailcomposer");
var connection = new SMTPConnection(options);
connection.connect(function (err) {
  console.log('Connected to SMTP server.');
  connection.login({
    user: 'foo',
    pass: 'bar'
  }, function (err) {
    if (err) {
      console.log('Authentication failed!', err);
    } else {
      console.log('Authentication to SMTP server successful.');
      var message = mailcomposer({
        from: 'dave@example.com',
        to: 'dave@example.com',
        subject: 'A test subject.',
        text: 'A test body.'
      });
      connection.send({
        from: 'dave@example.com',
        to: 'dave@example.com'
      }, message.createReadStream(), function (err, info) {
        if (err) {
          console.log('Message not sent.', err);
        } else {
          console.log('Message sent.', info);
        }
      });
    }
  });
});
```
Here is the console output log:
```bash
 artz@airtz  ~/Sites/smtp-server  node smtp.js
[2016-06-05 14:33:11] INFO: SMTP Server listening on [::]:2500
SMTP server listening on port 2500.
[2016-06-05 14:33:11] INFO: [txlxMgMHDTc] Connection established to 127.0.0.1:2500
[2016-06-05 14:33:11] INFO: [E/f6A62SIxii] Connection from [::ffff:127.0.0.1]
[2016-06-05 14:33:11] DEBUG: [E/f6A62SIxii] S: 220 airtz.fios-router.home ESMTP
[2016-06-05 14:33:11] DEBUG: [txlxMgMHDTc] S: 220 airtz.fios-router.home ESMTP
[2016-06-05 14:33:11] DEBUG: [txlxMgMHDTc] C: EHLO airtz.fios-router.home
[2016-06-05 14:33:11] DEBUG: [E/f6A62SIxii] C: EHLO airtz.fios-router.home
[2016-06-05 14:33:11] DEBUG: [E/f6A62SIxii] S: 250-OK: Nice to meet you [::ffff:127.0.0.1]
250-PIPELINING
250-8BITMIME
250-SMTPUTF8
250 AUTH PLAIN
[2016-06-05 14:33:11] DEBUG: [txlxMgMHDTc] S: 250-OK: Nice to meet you [::ffff:127.0.0.1]
250-PIPELINING
250-8BITMIME
250-SMTPUTF8
250 AUTH PLAIN
[2016-06-05 14:33:11] DEBUG: [txlxMgMHDTc] SMTP handshake finished
Connected to SMTP server.
[2016-06-05 14:33:11] DEBUG: [txlxMgMHDTc] C: AUTH PLAIN AGZvbwBiYXI=
[2016-06-05 14:33:11] DEBUG: [E/f6A62SIxii] C: AUTH PLAIN AGZvbwBiYXI=
Logging in `foo`.
[2016-06-05 14:33:11] INFO: [E/f6A62SIxii] foo authenticated using PLAIN
[2016-06-05 14:33:11] DEBUG: [E/f6A62SIxii] S: 235 Authentication successful
[2016-06-05 14:33:11] DEBUG: [txlxMgMHDTc] S: 235 Authentication successful
[2016-06-05 14:33:11] INFO: [txlxMgMHDTc] User "foo" authenticated
Authentication to SMTP server successful.
[2016-06-05 14:33:11] DEBUG: [txlxMgMHDTc] C: MAIL FROM:<dave@example.com>
[2016-06-05 14:33:11] DEBUG: [E/f6A62SIxii] C: MAIL FROM:<dave@example.com>
[2016-06-05 14:33:11] DEBUG: [E/f6A62SIxii] S: 250 Accepted
[2016-06-05 14:33:11] DEBUG: [txlxMgMHDTc] S: 250 Accepted
[2016-06-05 14:33:11] DEBUG: [txlxMgMHDTc] C: RCPT TO:<dave@example.com>
[2016-06-05 14:33:11] DEBUG: [E/f6A62SIxii] C: RCPT TO:<dave@example.com>
[2016-06-05 14:33:11] DEBUG: [E/f6A62SIxii] S: 250 Accepted
[2016-06-05 14:33:11] DEBUG: [txlxMgMHDTc] S: 250 Accepted
[2016-06-05 14:33:11] DEBUG: [txlxMgMHDTc] C: DATA
[2016-06-05 14:33:11] DEBUG: [E/f6A62SIxii] C: DATA
[2016-06-05 14:33:11] DEBUG: [E/f6A62SIxii] S: 354 End data with <CR><LF>.<CR><LF>
[2016-06-05 14:33:11] DEBUG: [txlxMgMHDTc] S: 354 End data with <CR><LF>.<CR><LF>
[2016-06-05 14:33:11] DEBUG: [txlxMgMHDTc] C: Content-Type: text/plain
From: dave@example.com
To: dave@example.com
Subject: A test subject.
Message-Id: <1465137191276-9ee02c38-e90e5898-e90c6e4c@example.com>
Content-Transfer-Encoding: 7bit
Date: Sun, 05 Jun 2016 14:33:11 +0000
MIME-Version: 1.0

[2016-06-05 14:33:11] DEBUG: [txlxMgMHDTc] C: A test body.
[2016-06-05 14:33:11] DEBUG: [txlxMgMHDTc] C:
.
[2016-06-05 14:33:11] INFO: [txlxMgMHDTc] C: <282 bytes encoded mime message (source size 277 bytes)>
[2016-06-05 14:33:11] INFO: <received 277 bytes>
[2016-06-05 14:33:11] DEBUG: [E/f6A62SIxii] C: <277 bytes of DATA>
[2016-06-05 14:33:11] DEBUG: [E/f6A62SIxii] S: 250 OK: message queued
[2016-06-05 14:33:11] DEBUG: [txlxMgMHDTc] S: 250 OK: message queued
Message sent. { accepted: [ 'dave@example.com' ],
  rejected: [],
  response: '250 OK: message queued' }
[2016-06-05 14:34:11] DEBUG: [E/f6A62SIxii] S: 451 Timeout - closing connection
[2016-06-05 14:34:11] DEBUG: [txlxMgMHDTc] S: 451 Timeout - closing connection
[2016-06-05 14:34:11] ERROR: [txlxMgMHDTc] Unexpected Response: 451 Timeout - closing connection
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected Response: 451 Timeout - closing connection
    at SMTPConnection._processResponse (/Users/artz/Sites/smtp-server/node_modules/smtp-connection/lib/smtp-connection.js:625:30)
    at SMTPConnection._onData (/Users/artz/Sites/smtp-server/node_modules/smtp-connection/lib/smtp-connection.js:449:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
```
Even though it says the message was queued successfully, it never arrives in my inbox (gmail account).

I'm also not sure how to correctly handle the timeout error.  

Thanks in advance for your assistance and guidance!

**Comment by dex4er** [comment]
@artzstudio You forgot to call `connection.quit()` after `connection.send()`.

You can handle timeouts in that way:

```
connection.on('error', (err) => {
  if (err.code === 'ETIMEDOUT') {
    console.log('SMTP session is timeouted');
  }
});
```

**Comment by artzstudio** [comment]
I updated the `connection.send` code to this:

```javascript
connection.send({
        from: 'daveartz@gmail.com',
        to: 'daveartz@gmail.com'
      }, message.createReadStream(), function (err, info) {
        if (err) {
          console.log('Message not sent.', err);
        } else {
          console.log('Message sent.', info);
        }
        connection.quit();
});
```
The log now looks like this:

```bash
Message sent. { accepted: [ 'artzstudio@gmail.com' ],
  rejected: [],
  response: '250 OK: message queued' }
[2016-06-06 00:48:25] DEBUG: [jPo0gvGaqE] C: QUIT
[2016-06-06 00:48:25] DEBUG: [7lFk0NkO8Jq+] C: QUIT
[2016-06-06 00:48:25] DEBUG: [7lFk0NkO8Jq+] S: 221 Bye
[2016-06-06 00:48:25] DEBUG: [jPo0gvGaqE] S: 221 Bye
[2016-06-06 00:48:25] DEBUG: [jPo0gvGaqE] Closing connection to the server using "end"
[2016-06-06 00:48:25] INFO: [jPo0gvGaqE] Connection closed
[2016-06-06 00:48:25] INFO: [7lFk0NkO8Jq+] Connection closed to [::ffff:127.0.0.1]
```
However the mail still doesn't show up in the target email account (tried multiple emails just in case).  Anything else I might be missing?

**Comment by andris9** [comment]
It seems you are trying to use smtp-server as a relay. This does not work like this. smtp-server allows your application to accept messages through the SMTP protocol but if you want to relay messages to some other destination then you need to write your own logic for it. When someone sends a message you get a data stream for it (see [here](https://github.com/andris9/smtp-server/blob/master/examples/server.js#L98-L109)). What you do with that stream is your own concern (maybe store it to disk, maybe process it somehow in memory, etc.)

**Comment by artzstudio** [comment]
Ah, knew I was somehow making the wrong assumption.  Do you have a recommended project for relaying the mail?  Thanks for clarifying.

**Comment by andris9** [comment]
Just use Postfix or any other standard e-mail servers. If you only want a relay then you do not need programmable access that you would get from a library like smtp-server.

**Comment by artzstudio** [comment]
FWIW, I do need programmable access to examine the contents of the email before sending along an alert to another address.
